server:
  port: 8088
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10
  servlet:
    context-path: /api

# 微信公众号对接
#weixin:
#  config:
#    originalid: gh_e067c267e056
#    token: b8b6
#    app-id: wx5a228ff69e28a91f
#    app-secret: 0bea03aa1310bac050aae79dd8703928
#    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

spring:
  datasource:
    username: root
    password: ezreal
    url: jdbc:mysql://127.0.0.1:3306/small-payment?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000125624045
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfrfC336UDRnr26XXQn1E7Ak5lkZsFHlayPpU5N93GxkjrgTQaQQI+cEqe6UTToEm/YNlfSmtyitBDpI8goOBGbRAS4b9lQj9JrOiPF/Fvz31RkX2T4/E68cTRNBUSLnsC2BgoWVFOcl7Gmz0y+LrL5oOIFltISlgz5YeU/FR+7Cg6Hf5gOdrYTzEc4F8Fh8E3wxD55ebwxLRafz5H+dr8JZqegvRO3J6Z0fzMqXf3Ejrc+2Qn2ZCgH1XT/GrmTp9imIxzL/JxKhuuGlONfvRrEP06sEGHHLcZrhSB0/9IF5vm/XlcIyUCnK+I04yWh9VT/XbOYX9dC6VzbBNIN+O9AgMBAAECggEAFHgGoHtxuq7BOn+I07pofkj4Zbq5hXlzIZw2IsSPkFiApnfEhw0ITZq1ZhN++CXW7kpq8vUmOuOieNlSY5tbxItcgR8hGsjYNgiNMzKdh3iwltEwqNGSbbzqPusPPGpq6F1tE1cHvieZEJp7yNnrkBG3kK1U/DpTfiuRKr8B0dcdVUVIt/LOqDRnk05dYpNdS6w98LByjsGqec6I/iv1n/+bW7g4VJtHuSOB+bT1K4amAcMFYb3AKOEzMFbjrjEhKIxykMv7O9S/y3Tp7hDCAxAdOocd68M1WPCdhnG8F1BQEoLwslBnOQxuTKF11gSXK3LiVegUZUoVZAcclcP7/QKBgQDxe47v+ErPD5c2vPFDtSHb1Eeq3Pu6vD1D3RWRDbYxpFymPip6/7ZkLiYiarVZozRIgeJCo9MSg5GQzmnuunT/BuR6IUjLKkuCVuBTvl3tGVrH7tYdfqhrTcwemxZnW7iZ3c94UesdwucXxXgPpShHL8vmtesnFHRkKbgURM0vTwKBgQCpR2w5+YQCCFAiXRJIDLIU1U+m7iCmbKcX5EmvxAg/BoHxUbN+bxDjKjWOGm+/2RFt2UD0RW5BNUlbS8dS6LHB8uPJwd95MVs+QIC+qM3WDO5r0pdcmAGvd7f0hztOkwsyVxkAi2tjgYpnEOrY5P0IHzHIYn96N//JIZX+EotZMwKBgGrb+3ezjx8rzgV5/OWyXOZTfNdebMLIk+/ZALcssygqjJlAPzoouESCq3tlbxTYhMVlPIOyzS+PKzZCMVxkBGvqV+a3nefRspJd8Wz9e8D1DFgXF4b7ynmZdq9Af9yDGSB1qF6dGYcU/YBmcOezdSxzOS7B5+pmQc8lKwFFJOs/AoGAE6QJ1qAwxNuaEKKj4GA4uVoWp9OxTh4FNSxzsEUaf9WNdiZ4oQ7Z8sGO/THsDWJuN0Sh2LXFmSNJo6IjOmdtWIeKDnrEJxem8o4hYf3MBC3z6+a/USsB5w4I9gJKy08cWXbpm7qRdzYsjNDVrtzCzxJvgESNbezZbMjM0nHsYSkCgYBYRdh6JowZDkYi1atarHEBTytOoZAZVa26Iv4l4Nybf0WT9E9crosfQzsftQBycxPuoqlzTC7ItZTvDifZHugVeqzVOLBy2n7eaBGaIwoLDWnzAPP1MAvPDmCsr+gXWDlMBsVxk5IybrdtJdF2hn9hYXRaqmBqeRuYk4YQeGBQSw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9FEZlaCniSh/aWhkDbiN3QlDlXF+HHoNkL6z5N7xNOsFb+OOMMxfULamnvd3pClNCx8RdsfIfp5QnSE2vpW6nEshyZwtBtxczbJ5bvIgjqE7sP99vjrhE/Prh59x5fpjtWvzkv5qusv6fyYLxyqqlWEW0y2OgInA+bJ+E/OxRGclMkCVCm24V0DI+nLPqoD2tdU7U6aAliIyUFhp2314PMAx/aoEdEZ0JIkA2/Kl9utv0oENHuzFV3qJb9nQrO7KUHO3sT4uqekm2MrPes6rooBsa1GIdij3X3FoXL18Q9LkjDbnw34wZRTPbfPhwc+wARA8wPAn/JIN16R2f2qcQIDAQAB
  notify_url: http://ezreal-payment.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign_type: RSA2
  charset: utf-8
  format: json

# 日志
#logging:
#  level:
#    root: info
#  config: classpath:logback-spring.xml