spring:
  config:
    name: small-payment
  profiles:
    active: dev


wechat:
  config:
    appId: wx1828227708d0fa29
    secret: 7b118c7ad626df7f2c630bd99fd17aa5
    originalId: gh_ffe6988c3a20
    token: "ezreal"